import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const geistMono = localFont({
  src: "../public/fonts/GeistMono-Regular.ttf", // kendi font dosya yolun
  variable: "--font-geist-mono",
});
const geistSans = localFont({
  src: "../public/fonts/Geist-Regular.ttf", // kendi font dosya yolun
  variable: "--font-geist",
});
const dmSans = localFont({
  src: "../public/fonts/DMSans-Regular.ttf", // kendi font dosya yolun
  variable: "--font-dmSans",
});

// const dmSans = DM_Sans({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-dm-sans",
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
html {
  font-family: ${geistSans.style.fontFamily};
  --font-sans: ${geistSans.variable};
  --font-mono: ${geistMono.variable};
  --font-dm-sans: ${dmSans.variable};
}
        `}</style>
      </head>
      <body className={dmSans.variable}>{children}</body>
    </html>
  );
}
